"""add company_profile table

Revision ID: 1b44daeabafc
Revises: 1dc937aef24b
Create Date: 2026-04-14 00:14:21.688789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b44daeabafc'
down_revision: Union[str, None] = '1dc937aef24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('tagline', sa.String(length=300), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=300), nullable=True),
    sa.Column('address_line2', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('bank_account_name', sa.String(length=200), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('bank_branch', sa.String(length=200), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('default_terms', sa.Text(), nullable=True),
    sa.Column('material_specs', sa.Text(), nullable=True),
    sa.Column('prepared_by', sa.String(length=200), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('owner_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profile_id'), 'company_profile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_profile_id'), table_name='company_profile')
    op.drop_table('company_profile')
    # ### end Alembic commands ###
