"""add wo_id to cutting_patterns

Revision ID: 28b4536f13ca
Revises: 9c107aa5373d
Create Date: 2026-04-10 09:22:16.408810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b4536f13ca'
down_revision: Union[str, None] = '9c107aa5373d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cutting_patterns', sa.Column('wo_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cutting_patterns_wo_id'), 'cutting_patterns', ['wo_id'], unique=False)
    op.create_foreign_key(None, 'cutting_patterns', 'work_orders', ['wo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cutting_patterns', type_='foreignkey')
    op.drop_index(op.f('ix_cutting_patterns_wo_id'), table_name='cutting_patterns')
    op.drop_column('cutting_patterns', 'wo_id')
    # ### end Alembic commands ###
