"""add cutlist optimizer tables

Revision ID: 5147f420c776
Revises: 28b4536f13ca
Create Date: 2026-04-12 19:51:22.450266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5147f420c776'
down_revision: Union[str, None] = '28b4536f13ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cut_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('sheet_width', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sheet_height', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('blade_kerf', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('kerf_unit', sa.Enum('MM', 'INCHES', name='cutunits'), nullable=False),
    sa.Column('cut_orientation', sa.Enum('LENGTH_FIRST', 'WIDTH_FIRST', name='cutorientation'), nullable=False),
    sa.Column('cutting_method', sa.Enum('GUILLOTINE', 'FREE', name='cuttingmethod'), nullable=False),
    sa.Column('optimization_priority', sa.Enum('MINIMIZE_WASTE', 'MINIMIZE_CUTS', name='optimizationpriority'), nullable=False),
    sa.Column('units', sa.Enum('MM', 'INCHES', name='cutunits'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OPTIMIZED', 'ARCHIVED', name='cutjobstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['raw_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cut_jobs_id'), 'cut_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_cut_jobs_material_id'), 'cut_jobs', ['material_id'], unique=False)
    op.create_table('cut_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cut_job_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('grain_locked', sa.Boolean(), nullable=False),
    sa.Column('edge_banding_l1', sa.Boolean(), nullable=False),
    sa.Column('edge_banding_l2', sa.Boolean(), nullable=False),
    sa.Column('edge_banding_w1', sa.Boolean(), nullable=False),
    sa.Column('edge_banding_w2', sa.Boolean(), nullable=False),
    sa.Column('rotation_locked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cut_job_id'], ['cut_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cut_parts_cut_job_id'), 'cut_parts', ['cut_job_id'], unique=False)
    op.create_index(op.f('ix_cut_parts_id'), 'cut_parts', ['id'], unique=False)
    op.create_table('cut_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cut_job_id', sa.Integer(), nullable=False),
    sa.Column('sheets_used', sa.Integer(), nullable=False),
    sa.Column('waste_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('material_efficiency_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('waste_area', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('placements_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('svg_data_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cut_job_id'], ['cut_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cut_job_id')
    )
    op.create_index(op.f('ix_cut_results_id'), 'cut_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cut_results_id'), table_name='cut_results')
    op.drop_table('cut_results')
    op.drop_index(op.f('ix_cut_parts_id'), table_name='cut_parts')
    op.drop_index(op.f('ix_cut_parts_cut_job_id'), table_name='cut_parts')
    op.drop_table('cut_parts')
    op.drop_index(op.f('ix_cut_jobs_material_id'), table_name='cut_jobs')
    op.drop_index(op.f('ix_cut_jobs_id'), table_name='cut_jobs')
    op.drop_table('cut_jobs')
    # ### end Alembic commands ###
