"""initial

Revision ID: 6bebb9fb9ca1
Revises: 
Create Date: 2026-04-03 09:33:06.337997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bebb9fb9ca1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('communication_log', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('documents', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('escalation_trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('reminder_count', sa.Integer(), nullable=False),
    sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_escalation_entity', 'escalation_trackers', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_escalation_pending', 'escalation_trackers', ['resolved', 'next_reminder_at'], unique=False)
    op.create_index(op.f('ix_escalation_trackers_id'), 'escalation_trackers', ['id'], unique=False)
    op.create_table('item_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_item_categories_id'), 'item_categories', ['id'], unique=False)
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('production_stages', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('EMPLOYEE', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_po_threshold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('auto_approve_wo_threshold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('supply_categories', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_table('approval_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('PURCHASE_ORDER', 'WORK_ORDER', 'DISPATCH', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', 'AUTO_APPROVED', 'RESUBMITTED', name='approvalaction'), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('auto_approve_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_logs_entity', 'approval_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_approval_logs_id'), 'approval_logs', ['id'], unique=False)
    op.create_index(op.f('ix_approval_logs_performed_by'), 'approval_logs', ['performed_by'], unique=False)
    op.create_table('finished_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.Enum('PCS', 'SQM', 'SET', name='productunit'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finished_products_category_id'), 'finished_products', ['category_id'], unique=False)
    op.create_index(op.f('ix_finished_products_id'), 'finished_products', ['id'], unique=False)
    op.create_index(op.f('ix_finished_products_sku'), 'finished_products', ['sku'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('APPROVAL_REQUEST', 'APPROVAL_REMINDER', 'ESCALATION', 'REORDER_ALERT', 'DELIVERY_COMPLETE', 'GENERAL', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('channel', sa.Enum('PUSH', 'WHATSAPP', 'SMS', 'IN_APP', name='notificationchannel'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('site_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_completion_date', sa.Date(), nullable=True),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_index(op.f('ix_projects_created_by'), 'projects', ['created_by'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_project_number'), 'projects', ['project_number'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=20), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'SENT_TO_VENDOR', 'PARTIALLY_RECEIVED', 'FULLY_RECEIVED', 'CANCELLED', name='postatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejection_count', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_created_by'), 'purchase_orders', ['created_by'], unique=False)
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_table('raw_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.Enum('PCS', 'SQM', 'M', 'KG', 'PAIR', 'LITRE', 'SET', name='materialunit'), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_purchase_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('current_stock >= 0', name='ck_raw_materials_stock_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_materials_category_id'), 'raw_materials', ['category_id'], unique=False)
    op.create_index(op.f('ix_raw_materials_id'), 'raw_materials', ['id'], unique=False)
    op.create_index(op.f('ix_raw_materials_sku'), 'raw_materials', ['sku'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('bom_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per_unit', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['finished_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'raw_material_id', name='uq_bom_product_material')
    )
    op.create_index(op.f('ix_bom_items_id'), 'bom_items', ['id'], unique=False)
    op.create_index(op.f('ix_bom_items_product_id'), 'bom_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_bom_items_raw_material_id'), 'bom_items', ['raw_material_id'], unique=False)
    op.create_table('dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_number', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'LOADING_VERIFICATION', 'IN_TRANSIT', 'DELIVERY_VERIFICATION', 'DELIVERED', name='dispatchstatus'), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=True),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.Column('driver_phone', sa.String(length=20), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('delivery_city', sa.String(length=100), nullable=True),
    sa.Column('delivery_token', sa.String(length=100), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_used', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejection_count', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loading_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loading_confirmed_by', sa.Integer(), nullable=True),
    sa.Column('delivery_marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_confirmed_by', sa.Integer(), nullable=True),
    sa.Column('challan_url', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_confirmed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loading_confirmed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatches_created_by'), 'dispatches', ['created_by'], unique=False)
    op.create_index(op.f('ix_dispatches_delivery_token'), 'dispatches', ['delivery_token'], unique=True)
    op.create_index(op.f('ix_dispatches_dispatch_number'), 'dispatches', ['dispatch_number'], unique=True)
    op.create_index(op.f('ix_dispatches_id'), 'dispatches', ['id'], unique=False)
    op.create_index(op.f('ix_dispatches_project_id'), 'dispatches', ['project_id'], unique=False)
    op.create_table('goods_received_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_number', sa.String(length=20), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_received_notes_grn_number'), 'goods_received_notes', ['grn_number'], unique=True)
    op.create_index(op.f('ix_goods_received_notes_id'), 'goods_received_notes', ['id'], unique=False)
    op.create_index(op.f('ix_goods_received_notes_po_id'), 'goods_received_notes', ['po_id'], unique=False)
    op.create_index(op.f('ix_goods_received_notes_received_by'), 'goods_received_notes', ['received_by'], unique=False)
    op.create_index(op.f('ix_goods_received_notes_vendor_id'), 'goods_received_notes', ['vendor_id'], unique=False)
    op.create_table('project_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PRODUCTION', 'COMPLETED', 'DISPATCHED', 'DELIVERED', name='projectitemstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['finished_products.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_items_id'), 'project_items', ['id'], unique=False)
    op.create_index(op.f('ix_project_items_product_id'), 'project_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_project_items_project_id'), 'project_items', ['project_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_purchase_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('received_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_id'), 'purchase_order_items', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_po_id'), 'purchase_order_items', ['po_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_raw_material_id'), 'purchase_order_items', ['raw_material_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wo_number', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='wostatus'), nullable=False),
    sa.Column('estimated_material_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejection_count', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bom_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_created_by'), 'work_orders', ['created_by'], unique=False)
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    op.create_index(op.f('ix_work_orders_project_id'), 'work_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_work_orders_wo_number'), 'work_orders', ['wo_number'], unique=True)
    op.create_table('dispatch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('project_item_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('factory_verified', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['finished_products.id'], ),
    sa.ForeignKeyConstraint(['project_item_id'], ['project_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_items_dispatch_id'), 'dispatch_items', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_dispatch_items_id'), 'dispatch_items', ['id'], unique=False)
    op.create_index(op.f('ix_dispatch_items_product_id'), 'dispatch_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_dispatch_items_project_item_id'), 'dispatch_items', ['project_item_id'], unique=False)
    op.create_table('grn_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('po_item_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('ordered_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('accepted_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rejected_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quality_status', sa.Enum('ACCEPTED', 'PARTIAL', 'REJECTED', name='qualitystatus'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['grn_id'], ['goods_received_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_item_id'], ['purchase_order_items.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grn_items_grn_id'), 'grn_items', ['grn_id'], unique=False)
    op.create_index(op.f('ix_grn_items_id'), 'grn_items', ['id'], unique=False)
    op.create_index(op.f('ix_grn_items_po_item_id'), 'grn_items', ['po_item_id'], unique=False)
    op.create_index(op.f('ix_grn_items_raw_material_id'), 'grn_items', ['raw_material_id'], unique=False)
    op.create_table('inventory_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_remaining', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('quantity_remaining >= 0', name='ck_batch_remaining_positive'),
    sa.ForeignKeyConstraint(['grn_id'], ['goods_received_notes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_batches_grn_id'), 'inventory_batches', ['grn_id'], unique=False)
    op.create_index(op.f('ix_inventory_batches_id'), 'inventory_batches', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_batches_raw_material_id'), 'inventory_batches', ['raw_material_id'], unique=False)
    op.create_table('work_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='woitemstatus'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['finished_products.id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_items_id'), 'work_order_items', ['id'], unique=False)
    op.create_index(op.f('ix_work_order_items_product_id'), 'work_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_work_order_items_wo_id'), 'work_order_items', ['wo_id'], unique=False)
    op.create_table('dispatch_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('dispatch_item_id', sa.Integer(), nullable=True),
    sa.Column('checkpoint', sa.Enum('FACTORY', 'SITE', name='photocheckpoint'), nullable=False),
    sa.Column('item_reference', sa.String(length=100), nullable=False),
    sa.Column('storage_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gps_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('gps_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('gps_available', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_role', sa.Enum('EMPLOYEE', 'DRIVER', name='photouploaderrole'), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dispatch_item_id'], ['dispatch_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_photos_dispatch_id'), 'dispatch_photos', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_dispatch_photos_dispatch_item_id'), 'dispatch_photos', ['dispatch_item_id'], unique=False)
    op.create_index(op.f('ix_dispatch_photos_id'), 'dispatch_photos', ['id'], unique=False)
    op.create_table('finished_good_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('wo_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('IN_STOCK', 'DISPATCHED', 'DELIVERED', name='fgstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('quantity >= 0', name='ck_fg_inventory_quantity_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['finished_products.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ),
    sa.ForeignKeyConstraint(['wo_item_id'], ['work_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finished_good_inventory_id'), 'finished_good_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_finished_good_inventory_product_id'), 'finished_good_inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_finished_good_inventory_project_id'), 'finished_good_inventory', ['project_id'], unique=False)
    op.create_index(op.f('ix_finished_good_inventory_wo_id'), 'finished_good_inventory', ['wo_id'], unique=False)
    op.create_index(op.f('ix_finished_good_inventory_wo_item_id'), 'finished_good_inventory', ['wo_item_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.Enum('GRN_IN', 'WO_ISSUE', 'WO_RETURN', 'ADJUSTMENT', 'WASTAGE', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('qty_before', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('qty_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_batch_id'), 'inventory_movements', ['batch_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_id'), 'inventory_movements', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_performed_by'), 'inventory_movements', ['performed_by'], unique=False)
    op.create_index(op.f('ix_inventory_movements_raw_material_id'), 'inventory_movements', ['raw_material_id'], unique=False)
    op.create_index('ix_inventory_movements_reference', 'inventory_movements', ['reference_type', 'reference_id'], unique=False)
    op.create_table('material_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity_issued', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('issued_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_issues_batch_id'), 'material_issues', ['batch_id'], unique=False)
    op.create_index(op.f('ix_material_issues_id'), 'material_issues', ['id'], unique=False)
    op.create_index(op.f('ix_material_issues_issued_by'), 'material_issues', ['issued_by'], unique=False)
    op.create_index(op.f('ix_material_issues_raw_material_id'), 'material_issues', ['raw_material_id'], unique=False)
    op.create_index(op.f('ix_material_issues_wo_id'), 'material_issues', ['wo_id'], unique=False)
    op.create_table('production_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wo_item_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='productionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['wo_item_id'], ['work_order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_units_id'), 'production_units', ['id'], unique=False)
    op.create_index(op.f('ix_production_units_wo_item_id'), 'production_units', ['wo_item_id'], unique=False)
    op.create_table('production_stage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_unit_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'COMPLETED', name='stagestatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['production_unit_id'], ['production_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_stage_logs_id'), 'production_stage_logs', ['id'], unique=False)
    op.create_index(op.f('ix_production_stage_logs_production_unit_id'), 'production_stage_logs', ['production_unit_id'], unique=False)
    op.create_table('wastage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_unit_id', sa.Integer(), nullable=True),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('logged_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['production_unit_id'], ['production_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wastage_logs_id'), 'wastage_logs', ['id'], unique=False)
    op.create_index(op.f('ix_wastage_logs_logged_by'), 'wastage_logs', ['logged_by'], unique=False)
    op.create_index(op.f('ix_wastage_logs_production_unit_id'), 'wastage_logs', ['production_unit_id'], unique=False)
    op.create_index(op.f('ix_wastage_logs_raw_material_id'), 'wastage_logs', ['raw_material_id'], unique=False)
    op.create_index(op.f('ix_wastage_logs_wo_id'), 'wastage_logs', ['wo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wastage_logs_wo_id'), table_name='wastage_logs')
    op.drop_index(op.f('ix_wastage_logs_raw_material_id'), table_name='wastage_logs')
    op.drop_index(op.f('ix_wastage_logs_production_unit_id'), table_name='wastage_logs')
    op.drop_index(op.f('ix_wastage_logs_logged_by'), table_name='wastage_logs')
    op.drop_index(op.f('ix_wastage_logs_id'), table_name='wastage_logs')
    op.drop_table('wastage_logs')
    op.drop_index(op.f('ix_production_stage_logs_production_unit_id'), table_name='production_stage_logs')
    op.drop_index(op.f('ix_production_stage_logs_id'), table_name='production_stage_logs')
    op.drop_table('production_stage_logs')
    op.drop_index(op.f('ix_production_units_wo_item_id'), table_name='production_units')
    op.drop_index(op.f('ix_production_units_id'), table_name='production_units')
    op.drop_table('production_units')
    op.drop_index(op.f('ix_material_issues_wo_id'), table_name='material_issues')
    op.drop_index(op.f('ix_material_issues_raw_material_id'), table_name='material_issues')
    op.drop_index(op.f('ix_material_issues_issued_by'), table_name='material_issues')
    op.drop_index(op.f('ix_material_issues_id'), table_name='material_issues')
    op.drop_index(op.f('ix_material_issues_batch_id'), table_name='material_issues')
    op.drop_table('material_issues')
    op.drop_index('ix_inventory_movements_reference', table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_raw_material_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_performed_by'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_batch_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_finished_good_inventory_wo_item_id'), table_name='finished_good_inventory')
    op.drop_index(op.f('ix_finished_good_inventory_wo_id'), table_name='finished_good_inventory')
    op.drop_index(op.f('ix_finished_good_inventory_project_id'), table_name='finished_good_inventory')
    op.drop_index(op.f('ix_finished_good_inventory_product_id'), table_name='finished_good_inventory')
    op.drop_index(op.f('ix_finished_good_inventory_id'), table_name='finished_good_inventory')
    op.drop_table('finished_good_inventory')
    op.drop_index(op.f('ix_dispatch_photos_id'), table_name='dispatch_photos')
    op.drop_index(op.f('ix_dispatch_photos_dispatch_item_id'), table_name='dispatch_photos')
    op.drop_index(op.f('ix_dispatch_photos_dispatch_id'), table_name='dispatch_photos')
    op.drop_table('dispatch_photos')
    op.drop_index(op.f('ix_work_order_items_wo_id'), table_name='work_order_items')
    op.drop_index(op.f('ix_work_order_items_product_id'), table_name='work_order_items')
    op.drop_index(op.f('ix_work_order_items_id'), table_name='work_order_items')
    op.drop_table('work_order_items')
    op.drop_index(op.f('ix_inventory_batches_raw_material_id'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_id'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_grn_id'), table_name='inventory_batches')
    op.drop_table('inventory_batches')
    op.drop_index(op.f('ix_grn_items_raw_material_id'), table_name='grn_items')
    op.drop_index(op.f('ix_grn_items_po_item_id'), table_name='grn_items')
    op.drop_index(op.f('ix_grn_items_id'), table_name='grn_items')
    op.drop_index(op.f('ix_grn_items_grn_id'), table_name='grn_items')
    op.drop_table('grn_items')
    op.drop_index(op.f('ix_dispatch_items_project_item_id'), table_name='dispatch_items')
    op.drop_index(op.f('ix_dispatch_items_product_id'), table_name='dispatch_items')
    op.drop_index(op.f('ix_dispatch_items_id'), table_name='dispatch_items')
    op.drop_index(op.f('ix_dispatch_items_dispatch_id'), table_name='dispatch_items')
    op.drop_table('dispatch_items')
    op.drop_index(op.f('ix_work_orders_wo_number'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_project_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_created_by'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_purchase_order_items_raw_material_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_po_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_project_items_project_id'), table_name='project_items')
    op.drop_index(op.f('ix_project_items_product_id'), table_name='project_items')
    op.drop_index(op.f('ix_project_items_id'), table_name='project_items')
    op.drop_table('project_items')
    op.drop_index(op.f('ix_goods_received_notes_vendor_id'), table_name='goods_received_notes')
    op.drop_index(op.f('ix_goods_received_notes_received_by'), table_name='goods_received_notes')
    op.drop_index(op.f('ix_goods_received_notes_po_id'), table_name='goods_received_notes')
    op.drop_index(op.f('ix_goods_received_notes_id'), table_name='goods_received_notes')
    op.drop_index(op.f('ix_goods_received_notes_grn_number'), table_name='goods_received_notes')
    op.drop_table('goods_received_notes')
    op.drop_index(op.f('ix_dispatches_project_id'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_id'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_dispatch_number'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_delivery_token'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_created_by'), table_name='dispatches')
    op.drop_table('dispatches')
    op.drop_index(op.f('ix_bom_items_raw_material_id'), table_name='bom_items')
    op.drop_index(op.f('ix_bom_items_product_id'), table_name='bom_items')
    op.drop_index(op.f('ix_bom_items_id'), table_name='bom_items')
    op.drop_table('bom_items')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_raw_materials_sku'), table_name='raw_materials')
    op.drop_index(op.f('ix_raw_materials_id'), table_name='raw_materials')
    op.drop_index(op.f('ix_raw_materials_category_id'), table_name='raw_materials')
    op.drop_table('raw_materials')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_created_by'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_projects_project_number'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_by'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_finished_products_sku'), table_name='finished_products')
    op.drop_index(op.f('ix_finished_products_id'), table_name='finished_products')
    op.drop_index(op.f('ix_finished_products_category_id'), table_name='finished_products')
    op.drop_table('finished_products')
    op.drop_index(op.f('ix_approval_logs_performed_by'), table_name='approval_logs')
    op.drop_index(op.f('ix_approval_logs_id'), table_name='approval_logs')
    op.drop_index('ix_approval_logs_entity', table_name='approval_logs')
    op.drop_table('approval_logs')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_item_categories_id'), table_name='item_categories')
    op.drop_table('item_categories')
    op.drop_index(op.f('ix_escalation_trackers_id'), table_name='escalation_trackers')
    op.drop_index('ix_escalation_pending', table_name='escalation_trackers')
    op.drop_index('ix_escalation_entity', table_name='escalation_trackers')
    op.drop_table('escalation_trackers')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
