"""add cutting calculator: dimensions on products and materials, cutting_patterns table

Revision ID: 81446843523a
Revises: 069073049d8a
Create Date: 2026-04-09 09:36:25.176367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81446843523a'
down_revision: Union[str, None] = '069073049d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cutting_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('product_length', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('product_width', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('product_height', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('product_depth', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('panels', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('sheets_required', sa.Integer(), nullable=False),
    sa.Column('total_panel_area', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_sheet_area', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('wastage_area', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('wastage_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cost_per_sheet', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('edge_banding_length', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['finished_products.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cutting_patterns_id'), 'cutting_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_cutting_patterns_product_id'), 'cutting_patterns', ['product_id'], unique=False)
    op.add_column('finished_products', sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('finished_products', sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('finished_products', sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('finished_products', sa.Column('depth', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('raw_materials', sa.Column('sheet_length', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('raw_materials', sa.Column('sheet_width', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('raw_materials', sa.Column('thickness', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_materials', 'thickness')
    op.drop_column('raw_materials', 'sheet_width')
    op.drop_column('raw_materials', 'sheet_length')
    op.drop_column('finished_products', 'depth')
    op.drop_column('finished_products', 'height')
    op.drop_column('finished_products', 'width')
    op.drop_column('finished_products', 'length')
    op.drop_index(op.f('ix_cutting_patterns_product_id'), table_name='cutting_patterns')
    op.drop_index(op.f('ix_cutting_patterns_id'), table_name='cutting_patterns')
    op.drop_table('cutting_patterns')
    # ### end Alembic commands ###
