"""add factory address to company_profile

Revision ID: 857b61310bd3
Revises: 1b44daeabafc
Create Date: 2026-04-14 00:23:06.989852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857b61310bd3'
down_revision: Union[str, None] = '1b44daeabafc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profile', sa.Column('factory_address_line1', sa.String(length=300), nullable=True))
    op.add_column('company_profile', sa.Column('factory_address_line2', sa.String(length=300), nullable=True))
    op.add_column('company_profile', sa.Column('factory_city', sa.String(length=100), nullable=True))
    op.add_column('company_profile', sa.Column('factory_state', sa.String(length=100), nullable=True))
    op.add_column('company_profile', sa.Column('factory_pincode', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_profile', 'factory_pincode')
    op.drop_column('company_profile', 'factory_state')
    op.drop_column('company_profile', 'factory_city')
    op.drop_column('company_profile', 'factory_address_line2')
    op.drop_column('company_profile', 'factory_address_line1')
    # ### end Alembic commands ###
