"""add job_type and contractor fields to cutting_patterns

Revision ID: a78d990d2e5b
Revises: 81446843523a
Create Date: 2026-04-09 15:36:02.383194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a78d990d2e5b'
down_revision: Union[str, None] = '81446843523a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    jobtype_enum = sa.Enum('OWN', 'CONTRACT', name='jobtype')
    jobtype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('cutting_patterns', sa.Column('job_type', jobtype_enum, nullable=False, server_default='OWN'))
    op.add_column('cutting_patterns', sa.Column('company_name', sa.String(length=200), nullable=True))
    op.add_column('cutting_patterns', sa.Column('company_contact', sa.String(length=100), nullable=True))
    op.add_column('cutting_patterns', sa.Column('company_phone', sa.String(length=20), nullable=True))
    op.add_column('cutting_patterns', sa.Column('job_reference', sa.String(length=100), nullable=True))
    op.add_column('cutting_patterns', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cutting_patterns', 'notes')
    op.drop_column('cutting_patterns', 'job_reference')
    op.drop_column('cutting_patterns', 'company_phone')
    op.drop_column('cutting_patterns', 'company_contact')
    op.drop_column('cutting_patterns', 'company_name')
    op.drop_column('cutting_patterns', 'job_type')
    # ### end Alembic commands ###
