"""add expenses table

Revision ID: e6527ea11d0b
Revises: 6260857e4ba1
Create Date: 2026-04-05 22:07:00.861377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6527ea11d0b'
down_revision: Union[str, None] = '6260857e4ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('ELECTRICITY', 'RENT', 'LABOUR_WAGES', 'TRANSPORT', 'FUEL', 'MACHINE_MAINTENANCE', 'TOOLS', 'CONSUMABLES', 'PACKAGING', 'FOOD_REFRESHMENTS', 'TELEPHONE_INTERNET', 'INSURANCE', 'TAXES_FEES', 'SITE_INSTALLATION', 'MISCELLANEOUS', name='expensecategory'), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('CASH', 'UPI', 'BANK_TRANSFER', 'CHEQUE', 'CREDIT_CARD', name='paymentmode'), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expenses_category', 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_created_by'), 'expenses', ['created_by'], unique=False)
    op.create_index('ix_expenses_date', 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index('ix_expenses_project', 'expenses', ['project_id'], unique=False)
    op.create_index(op.f('ix_expenses_project_id'), 'expenses', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_project_id'), table_name='expenses')
    op.drop_index('ix_expenses_project', table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index('ix_expenses_date', table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_by'), table_name='expenses')
    op.drop_index('ix_expenses_category', table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
